# Generated by Django 3.2.13 on 2022-04-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.DateTimeField()),
                ('phoneCode', models.DateTimeField()),
                ('tag', models.CharField(max_length=100)),
                ('timeZone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('messageText', models.CharField(max_length=1000)),
                ('targetClient_PhoneCode', models.IntegerField()),
                ('targetClient_Tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDateTime', models.DateTimeField(editable=False)),
                ('status', models.CharField(max_length=100)),
                ('targetClient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailingApp.client')),
                ('targetMailing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailingApp.mailing')),
            ],
        ),
    ]
